### ISSUE TITLE
Test run is slow

### ISSUE THREAD

**Issue by ducan-ne** [web-infra-dev/midscene#110]
Each .ai() call takes ~5-8 seconds seems a bit slow, is there any way to speed it up?

**Comment by yuyutaotao** [comment]
It's mainly about the time of calling multi-modal LLM.

You can try the latest version 0.6.1. We have merged the planning process and the initial locating process in this version, which makes the `.ai` call a bit faster. 

Another approach is to use the cache in Playwright: https://midscenejs.com/docs/usage/cache.html

**Comment by ducan-ne** [comment]
@yuyutaotao I Understand that. I know we're calling an LLM and processing screenshots with OpenAI Vision. However, I noticed that the plan() function takes about 4 seconds. Is this normal? Do you have any benchmarks or averages from real-world use cases? Or could this be specific to my OpenAI account?

Obviously implemented the cache but the reality of a simple playwright script runs in less than a second vs openai nearly 1 minute is 😅 to me

![Image](https://github.com/user-attachments/assets/73a88f10-08f6-4579-b5fd-5043dec8bba7)

**Comment by yuyutaotao** [comment]
4 seconds for AI planning is a normal value. 

Have you tried the caching flag? After using the cache, the performance should be the same as that of plain JavaScript code.

**Comment by ducan-ne** [comment]
I tried but had to turn it off due to content is changing too frequently and I don't have control of content

Btw if 4s is about calling AI that would be fine, we couldn't handle OpenAI side, hopefully in the near future we can see a significant improvement

I going to close this issue now as it doesn't have any further thing to discuss.
