### ISSUE TITLE
AI 如何模拟拖拽这类功能

### ISSUE THREAD

**Issue by jackiealex** [web-infra-dev/midscene#174]
我有个登录需求，发现给出 aiAction('找到页面上的拖拽按钮，从按钮中心按下鼠标左键，将按钮从左边拖动到右边，然后松开鼠标左键') 这样的操作

实现不了我的需求啊

**Comment by yuyutaotao** [comment]
* 拖拽功能暂时还没有实现
* 目前的回放只有 Midscene 本体实现的部分，没有其他信息。可以考虑 Playwright 的 UI 能力去做回放。

**Comment by jackiealex** [comment]
硬伤。。。
