### ISSUE TITLE
How to implement a a 'goal-to-task' AI planning tool based on Midscene

### ISSUE THREAD

**Issue by ducan-ne** [web-infra-dev/midscene#181]
[The FAQ](https://midscenejs.com/faq.html#can-midscene-smartly-plan-the-actions-according-to-my-one-line-goal-like-executing-tweet-hello-world) mentioned 

> If you require a 'goal-to-task' AI planning tool, you can develop one based on Midscene.

But I'm not sure how to leverage Midscene to make this, any hint for this? Currently the AI trend is about use a goal instead defining atomic tasks like  this so I want to give it a try

**Comment by yuyutaotao** [comment]
Hi @ducan-ne ,
You may try the latest v0.8.6 version of midscene. We've just add some 'replanning' strategy in this version.

**Comment by yuyutaotao** [comment]
We will remove the "goals and tasks" instructions from the FAQ, as it is not straightforward for developers to implement.
