### ISSUE TITLE
chrome插件中如何支持Azure OPENAI，可以再详细一些吗

### ISSUE THREAD

**Issue by JinxQuQ** [web-infra-dev/midscene#191]
我按照教程配置输入了：
OPENAI_API_KEY="mykey"
OPENAI_API_VERSION="2024-08-06"
OPENAI_USE_AZURE="TRUE"
OPENAI_BASE_URL="https://MY_BASE_URL"

但还是提示
environment variable is missing or empty; either provide it, or instantiate the AzureOpenAI client with an apiVersion option, like new AzureOpenAI({ apiVersion: 'My API Version' }).
Error: The OPENAI_API_VERSION environment variable is missing or empty; either provide it, or instantiate the AzureOpenAI client with an apiVersion option, like new AzureOpenAI({ apiVersion: 'My API Version' }).

**Comment by yuyutaotao** [comment]
我在 @beta 版本上更新了一下支持 Azure 的环境变量（对着文档盲写的，我没有测试环境），有兴趣的话可以试试。

配置是这样的：
```
export MIDSCENE_USE_AZURE_OPENAI=1
export MIDSCENE_AZURE_OPENAI_SCOPE="https://cognitiveservices.azure.com/.default"
export MIDSCENE_AZURE_OPENAI_INIT_CONFIG_JSON='{"apiVersion": "2024-11-01-preview", "endpoint": "...", "deployment": "..."}'
```

但是这个没法在浏览器插件里跑通（`InteractiveBrowserCredential` 需要 OAuth 跳转，插件里感觉跑不通），你只能用 Yaml 脚本或者 JS 脚本去集成测试。

**Comment by JinxQuQ** [comment]
收到🫡非常感谢！
不过我后续拿到了正式的OPENAI_API_KEY，在本地尝试了一下，三种方式都连不上
`Error: Cannot find OpenAI config. You should set it before using. https://midscenejs.com/model-provider.html`
均尝试了在环境变量中配置 OpenAI API Key
`export OPENAI_API_KEY="xxx"`
以及在根目录新建并使用 .env 文件存储配置
`OPENAI_API_KEY="xxx"`

**Comment by yuyutaotao** [comment]
Error: Cannot find OpenAI config

这应该就是环境变量没生效吧 ，本地打印试试
```shell
echo $OPENAI_API_KEY
```
