### ISSUE TITLE
在openApi上申请了key，然后再chrome上安装扩展插件，填写OPENAI_API_KEY之后， 打开百度首页进行Action操作，出现404错误

### ISSUE THREAD

**Issue by luoyq-Rockey** [web-infra-dev/midscene#199]
在openApi上申请了key，然后再chrome上安装扩展插件，填写OPENAI_API_KEY之后， 打开百度首页进行Action操作，出现404错误
![Image](https://github.com/user-attachments/assets/1df0f901-2f31-4c85-b621-68c6a92657db)

**Comment by yuyutaotao** [comment]
配置问题，需要你自己排查了。可以参考文档：  https://midscenejs.com/zh/model-provider.html#%E8%B0%83%E8%AF%95-llm-%E6%9C%8D%E5%8A%A1%E8%BF%9E%E6%8E%A5%E9%97%AE%E9%A2%98

**Comment by luoyq-Rockey** [comment]
好的 谢谢~~

**Comment by zhangziyang960** [comment]
我也是这个问题 请问你解决了吗

**Comment by luoyq-Rockey** [comment]
> 我也是这个问题 请问你解决了吗
解决了，URL也需要配置，另外key可以单独访问一下，确保API key是正常的
