### ISSUE TITLE
问题咨询:使用YAML的方式配置场景，运行的时候提示:require('../dist/lib/index.js');

### ISSUE THREAD

**Issue by luoyq-Rockey** [web-infra-dev/midscene#202]
根据文档安装了
npm i -g @midscene/cli
将环境变量放置在 .env 文件中
midscene .\test.yaml --keep-window --header 运行测试代码 

![Image](https://github.com/user-attachments/assets/6c5ece2e-f5ba-4daa-b7af-787ea5093452)

提示这个
![Image](https://github.com/user-attachments/assets/f030da8d-eccb-4ca7-8a63-a40c985bbf0f)

**Comment by luoyq-Rockey** [comment]
另外一个问题，如果有登录的场景，应该怎么做呢，求答复~~谢谢

**Comment by yuyutaotao** [comment]
yaml 的问题，没看到命令行有具体报错？

看起来命令路径是错的，你的脚本是在  ./midscene-scripts\test.yaml ，少了一层目录

**Comment by yuyutaotao** [comment]
Playwright 的抛错，想不出是什么原因。

如果用原生的 test 方法替换截图里第二行的代码，能找到测试用例吗？现在 `No tests found` 看起来很奇怪

```
import { test as base } from '@playwright/test';
```

**Comment by luoyq-Rockey** [comment]
> yaml 的问题，没看到命令行有具体报错？
> 
> 看起来命令路径是错的，你的脚本是在 ./midscene-scripts\test.yaml ，少了一层目录

我这边把整个demo下载下来了，当前所处在的目录：PS D:\Midscene_P\midscene-example-main>
使用：midscene .\yaml-scripts-demo\midscene-scripts\test.yaml
还是出现相同的错误，有点郁闷了现在~

![Image](https://github.com/user-attachments/assets/216bf1a6-0b14-42ae-890f-69e4e31c8766)

**Comment by luoyq-Rockey** [comment]
> Playwright 的抛错，想不出是什么原因。
> 
> 如果用原生的 test 方法替换截图里第二行的代码，能找到测试用例吗？现在 `No tests found` 看起来很奇怪
> 
> ```
> import { test } from '@playwright/test';
> ```

用原生的替换之后，还是提示没有case，有点奇怪。希望能解答这个问题场景
我这边是测试，目前在调研做UI自动化的框架，对于JS这块不是很熟悉，只能照着demo做操作，如果有问的质量很低的问题，请理解，还请多多指教~~谢谢
![Image](https://github.com/user-attachments/assets/84f9c89a-9cf6-4b4b-8f14-12f4c9f9cd69)

**Comment by yuyutaotao** [comment]
好奇怪，感觉没思路了。

1. 是不是没有 cd 到 Playwright-demo 这个目录？
2. 直接用 Playwright 官方的初始化仓库跑一遍呢？

**Comment by luoyq-Rockey** [comment]
> 好奇怪，感觉没思路了。
> 
> 1. 是不是没有 cd 到 Playwright-demo 这个目录？
> 2. 直接用 Playwright 官方的初始化仓库跑一遍呢？

第一点，cd到这个目录下 试了下，问题场景一样的
![Image](https://github.com/user-attachments/assets/be3e51bd-2ee3-4449-84db-7de30eaa8115)

第二点
我下来需要自己去看看playwright的使用 

感谢答复~~

**Comment by luoyq-Rockey** [comment]
你好，关于yaml的那个问题，你那边本地测试的是 require('../dist/lib/index.js');  这个'../dist/lib/index.js'目录下的这个文件是什么东西来的呢？

**Comment by yuyutaotao** [comment]
这个就是  Midscene 包里的代码。很奇怪，它为什么会出现在浏览器里？

**Comment by luoyq-Rockey** [comment]
> 这个就是 Midscene 包里的代码。很奇怪，它为什么会出现在浏览器里？

有点尴尬，请问一下，你们有VX群或者QQ群这样类似的沟通群吗，感觉可以深入沟通一下场景，谢谢

**Comment by yuyutaotao** [comment]
文档上更新了一个飞书交流群：https://midscenejs.com/zh

但环境问题还得你自己想办法先解决掉（让 Playwright 官方用例跑起来）

**Comment by luoyq-Rockey** [comment]
PS D:\Midscene_P\midscene-example-main> npm list -g
d:\user\01416279\Application Data\npm
├── @midscene/cli@0.8.8
└── pnpm@9.15.1

是不是因为我本地没有安装Playwright导致的啊？

**Comment by luoyq-Rockey** [comment]
@yuyutaotao  npx playwright test .\tests\example.spec.js这样执行就会报 找不到tests的问题已解决
由于我使用的是windows，执行的时候 把\ 换成/ 就不报错了
yaml运行的方式我自己在看看， 谢谢
