### ISSUE TITLE
chrome插件无法正常运行

### ISSUE THREAD

**Issue by cybors** [web-infra-dev/midscene#207]
配置了：
OPENAI_API_KEY
OPENAI_BASE_URL
MIDSCENE_MODEL_NAME
输入prompt后 点击 run 提示：
Cannot access a chrome-extension:// URL of different extension
Error: Cannot access a chrome-extension:// URL of different extension

**Comment by yuyutaotao** [comment]
左侧界面得是一个普通的 https:// tab，不能是浏览器插件页面

**Comment by milkse** [comment]
![Image](https://github.com/user-attachments/assets/2f109319-ad86-47ff-b8b3-fa4d030b1f0b)
遇到同样问题，浏览器插件已全部关闭了，UI区也显示的是当前的页面

**Comment by yuyutaotao** [comment]
@milkse 你这个报错和楼主反馈的不一样，它就是一个 LLM 服务没连上的错误。打开 DevTool 看一下就知道了。

**Comment by cybors** [comment]
> 左侧界面得是一个普通的 https:// tab，不能是浏览器插件页面
![](https://ice.frostsky.com/2024/12/26/24da9bb0f5ed74587d13f102840718a3.png)
不太明白你说的什么意思，左侧必须是指定网址才可以？

**Comment by yuyutaotao** [comment]
知道了，应该是和别的插件有冲突。页面里有其他插件注入的 `<script />`。你用 devtool 看下页面的 dom，具体是那个插件 id 注入的 （格式： chrome-extension://{id} ，在 chrome://extensions/ 页面可以找到它对应的名字。

**Comment by cybors** [comment]
@yuyutaotao 
打断点后 catch(e4) 插件名称为midscene.js
Error: Assertion failed: click bratao
Reason: The 'activeTab' permission is not in effect because this extension has not been in invoked.
    at D.aiAssert (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/popup.js:1:2879147)
    at async Object.onClick (chrome-extension://gbldofcpkknbggpkmbdaefngejllnief/lib/popup.js:1:4006190)

**Comment by yuyutaotao** [comment]
顶上的报错不是这个么： `Error: Cannot access a chrome-extension:// URL of different extension` ，插件里打了断点之后，出现了另一个？

**Comment by yuyutaotao** [comment]
拿这个 action 产物里的压缩包试一下？这是还没发布的插件，小幅改动了了一下报错： https://github.com/web-infra-dev/midscene/actions/runs/12498481084

**Comment by cybors** [comment]
同样的报错：
![](https://ice.frostsky.com/2024/12/26/f7518a7f67da0d4662dc72441b76a3a0.png)

**Comment by yuyutaotao** [comment]
文档最后更新了插件冲突的排查方法，试一下？ https://midscenejs.com/zh/quick-experience.html

或者在隐身模式关闭其他所有插件

**Comment by cybors** [comment]
冲突的插件是 语雀的插件。
但是禁用插件后报了新的错误：【使用了豆包的模型】
500 The service encountered an unexpected internal error. Request id: 021735180482598fbe2fc2ef2347151a1c7d041f25883a8c0db6f
Error: 500 The service encountered an unexpected internal error. Request id: 021735180482598fbe2fc2ef2347151a1c7d041f25883a8c0db6f

**Comment by yuyutaotao** [comment]
赞 浏览器插件的问题算是解决了

豆包模型，确定配置正确么？ https://midscenejs.com/zh/model-provider.html

**Comment by cybors** [comment]
> 赞 浏览器插件的问题算是解决了
> 
> 豆包模型，确定配置正确么？ https://midscenejs.com/zh/model-provider.html

看了一下参数，应该是要支持图片内容理解的模型才可以。我以为是基于DOM实现的，是我配置的模型的原因。
      "content": [
        {
          "type": "image_url",
          "image_url": {
            "url": "data:image/png;base64,

**Comment by yuyutaotao** [comment]
赞，这个 issue 可以结束了

你也可以找其他模型比对看看效果，挑个好用的
