### ISSUE TITLE
我该如何配置豆包的api使其能够正常使用

### ISSUE THREAD

**Issue by ShaNan-KU** [web-infra-dev/midscene#209]
如图我在.env文件中配置了豆包api
但是在使用时会报401
Reason: 401 The API key or AK/SK in the request is missing or invalid. requestId: 0217351390011801bc9c5b75a94498bdb7e4ccd20bc00013c8c68

在使用connectivity-test工具时也是报401。
希望能够被解答

**Comment by ShaNan-KU** [comment]
在使用setx 指令设置后报错connection error，之前通过使用官方文档的“集成到 Puppeteer”样例，也是报connection error

**Comment by ShaNan-KU** [comment]
最新战报，通过chrome插件可以使用，并成功运行官方样例（ps配置的key是一模一样的）
![Image](https://github.com/user-attachments/assets/bfb01631-e5bf-4e21-9bd1-9ff50b34fe65)

**Comment by yuyutaotao** [comment]
@ShaNan-KU 晚些我看下。把截图删了吧，ak 不要写在 issue 里。

**Comment by ShaNan-KU** [comment]
> connectivity-test 的 401 也截图看下，有三个用例，挂掉的是前两个 or 后一个

![Image](https://github.com/user-attachments/assets/7d64ecfe-9ed3-4c88-95f4-92e609374c01)
全挂

**Comment by yuyutaotao** [comment]
tests/connectivity.test.ts  第17行左右有一行注释，打开它，打印一下 process.env，看看环境是否配上了。

打印结果不要贴上来，可能有敏感信息

**Comment by ShaNan-KU** [comment]
输出了配置的ak信息，但是上面有一句"OPENAI_API_KEY" is already defined and was NOT overwritten

**Comment by yuyutaotao** [comment]
说明环境里已经有这个配置了？

**Comment by ShaNan-KU** [comment]
根据提示来推断的话是这样，但不知道为啥会报401，就算有这个配置那也是一样的配置。或者有可能是我之前用的openai的key，现在换成了豆包的key，覆写不进去了

**Comment by ShaNan-KU** [comment]
可能是之前用的setx命令设置过该变量，我去尝试一下如何删除

**Comment by yuyutaotao** [comment]
应该是用 openai 的 key 去调用豆包了（base_url 已经指向了豆包），报 401  是合理的

**Comment by yuyutaotao** [comment]
dotenv 的策略默认是不会覆盖的，就是上面的提示 “is already defined and was NOT overwritten”

**Comment by ShaNan-KU** [comment]
已解决，感谢
