### ISSUE TITLE
在chrome插件中可以正常使用，但在playwright中使用时，报max_tokens超出限制。请问是哪里配置不对吗？谢谢

### ISSUE THREAD

**Issue by yi202306** [web-infra-dev/midscene#211]
![Image](https://github.com/user-attachments/assets/e03c7c3e-064b-46ea-8cb5-1b04422978fd)

**Comment by yuyutaotao** [comment]
什么模型？

**Comment by yuyutaotao** [comment]
模型选择的文档： https://midscenejs.com/zh/model-provider.html

**Comment by yi202306** [comment]
都是配置的阿里千问  qwen-vl-max-latest

**Comment by yuyutaotao** [comment]
代码里写了 max_token 3000

我们增加个配置项吧

**Comment by yi202306** [comment]
感谢、感谢~

**Comment by yuyutaotao** [comment]
发布了 ， 0.8.12 版本
应该不用新增配置，默认调到 2048 了，够用

**Comment by yi202306** [comment]
给力~

**Comment by yi202306** [comment]
> 发布了 ， 0.8.12 版本 应该不用新增配置，默认调到 2048 了，够用

 大佬，已经改配置了、也获取到了（如图），但好像还是用的2048，帮忙看看？谢谢。

![Image](https://github.com/user-attachments/assets/0cf013e5-2b3e-4b73-87ea-958dd28e84f5)

**Comment by yuyutaotao** [comment]
你改了什么配置？

**Comment by yi202306** [comment]
> 你改了什么配置？
在.env文件中，将最大token设置为4096，其他没动。
![Image](https://github.com/user-attachments/assets/6f115a6e-2b55-4190-beba-41dfd5bd1437)

**Comment by yuyutaotao** [comment]
看报错，你这个模型最大支持 2408，配了 4096 肯定不行啊....
