### ISSUE TITLE
[Connectivity] Dose it support openrouter api?

### ISSUE THREAD

**Issue by benji822** [web-infra-dev/midscene#215]
## Read this before open issue

- Doc: how to choose and config a model: https://midscenejs.com/model-provider.html
- Use this project to check the connection: https://github.com/web-infra-dev/midscene-example/tree/main/connectivity-test

## If the error persists, tell us these information

- Where are you using Midscene.js: Chrome extension, yaml with cli, Puppeteer,…
- The version of Midscene.js
- The model name and endpoint (if could be public）
- The error message
- Do NOT include your API key in your issue! Revoke it immediately if it is leaked in your issue.

**Comment by yuyutaotao** [comment]
This config should work

```bash
OPENAI_BASE_URL=https://openrouter.ai/api/v1
OPENAI_API_KEY=..
MIDSCENE_OPENAI_INIT_CONFIG_JSON='{"defaultHeaders":{"HTTP-Referer":"...","X-Title":"..."}}'
```
