### ISSUE TITLE
问题咨询：集成到 Playwright .env文件要放在哪个目录下

### ISSUE THREAD

**Issue by liyibug** [web-infra-dev/midscene#216]
![Image](https://github.com/user-attachments/assets/223d4da1-f005-42b3-af7e-7e752cc84431)
放在根目录和e2e目录下都提示找不到ai模型的配置

**Comment by yuyutaotao** [comment]
截图这个位置对的。
用 dotenv 加载一下就行了，截图文件里 1-8 行是什么内容？dotenv 配置改过？

**Comment by liyibug** [comment]
感谢回复 可以了  用 dotenv 加载了一下   文件里1-8行是他默认的注释

**Comment by yuyutaotao** [comment]
https://github.com/web-infra-dev/midscene-example/blob/main/playwright-demo/playwright.config.ts#L8

样例代码库，默认就会加载 dotenv 才对？ 是手动关错了吗？or我们搞错了什么？

**Comment by liyibug** [comment]
新建的playwright.config.ts 默认把 dotenv,config 给注释掉了

**Comment by liyibug** [comment]
> 新建的playwright.config.ts 默认把 dotenv,config 给注释掉了

可能是我关错了

**Comment by yuyutaotao** [comment]
好的
