### ISSUE TITLE
支持canvas绘画出来的内容执行ui自动化测试么

### ISSUE THREAD

**Issue by milkse** [web-infra-dev/midscene#220]

**Comment by yuyutaotao** [comment]
如果特别急用，有一个开发中的版本，你需要在浏览器中声明 canvas 中的内容，具体参考这个 PR 中的文档：https://github.com/web-infra-dev/midscene/pull/203

npm 版本：0.8.9-beta-20241227033828.0 
插件用这个：[Release · web-infra-dev/midscene@de60965](https://github.com/web-infra-dev/midscene/actions/runs/12511426913)


如果不是急用，可以等等我们后续迭代，有一些图像识别方案、模型在准备中了。

**Comment by milkse** [comment]
好的，谢谢

**Comment by yuyutaotao** [comment]
那这个 issue 先关了。如果要用上面的测试版、有疑问，可以另开一个 issue。
