### ISSUE TITLE
[Feature] AI waitFor

### ISSUE THREAD

**Issue by ducan-ne** [web-infra-dev/midscene#53]
Not sure if it's technically possible but it'd be great if we can use natural language to wait for the page condition
https://playwright.dev/docs/api/class-page#page-wait-for-function

Might be expensive in term of llm calls 🤔 

API usage idea
```typescript
await aiWaitFor("the loading spinner is off");

await aiWaitFor("the modal is closed");
```

**Comment by yuyutaotao** [comment]
yes, it may be expensive... We will add this API soon.

**Comment by yuyutaotao** [comment]
Considering the speed of LLM, maybe a simple `sleep` would be more effective.

**Comment by ducan-ne** [comment]
yeah currently I use wait for function that runs pretty nice, in my understanding it runs after any event occured (throttle).
Can't wait the future when LLM is cheap enough for this, or  we have another solution that solid

**Comment by yuyutaotao** [comment]
Hi, the `waitFor` has been released. 

You may refer to the document: https://midscenejs.com/docs/usage/API.html#aiwaitforassertion-string-timeoutms-number-checkintervalms-number----wait-until-the-assertion-is-met
